### PR TITLE
Hw git

### PR DESCRIPTION
**Pull request by ElenaZhelezova**

### CODE REVIEW

**Comment by SagurovA93** [comment]
I would ask you next time to create a README.md file and describe all steps there.

**Review by SagurovA93 — CHANGES_REQUESTED** [review]
Hello Elena! 
I have a few comments on this PR: 

1. I think this is not according to task: `Protect master branch to allow only maintainers to merge into it, and restrict all to push there`
image

2. I do not see the README.md file with commands you used to do this homework. I would like to know if you will update this PR with README.md? 

We can close this PR bit I cannot mark this homework as completed.

**Comment by ElenaZhelezova** [comment]
ok, I'll update it some time later - a lot of dockers working on my computer now, I can't run one more. i have a question about restrict all, does it mean that nobody could push?

**Review by SagurovA93 — APPROVED** [review]
Thank you, good work.
We can merge this PR,  but I have some questions for you: 
1. What will happen when your local GitLab docker container will stop? Will it keep configurations and code?
2. How to setup root password before Gitlabb starts?
3. Can you `push -f` to the protected branch as a maintainer or developer?

**Comment by ElenaZhelezova** [comment]
What will happen when your local GitLab docker container will stop? Will it keep configurations and code?
 - it won't if there isn't volume attached

How to setup root password before Gitlabb starts?
- Gitlab suggests to create password to login on start page

Can you push -f to the protected branch as a maintainer or developer?
- I think I can't

**Pull request merged**
